### ISSUE TITLE
Please update to latest versions

### ISSUE THREAD

**Issue by greduan** [georgeOsdDev/docpad-plugin-roole#1]
@georgeOsdDev It has been a long long while since you last updated the plugin. So I was wondering if you could update the dependencies and make sure that the plugin works with the latest version of DocPad.

Latest versions:
- Roole: v0.4.1
- Docpad: v6.46.5
- CoffeeScript: v1.6.3

If you could commit a dependency update that would be great. :)

**Comment by georgeOsdDev** [comment]
Update package dependencies :)

**Comment by greduan** [comment]
Thanks. :)
